server:
  port: 8264


spring:
  application:
    name: ppeng-module-search
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 # 10.0.0.88:7744  # Nacos服务注册中心地址
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**
    sentinel:
      transport:
        dashboard: 10.0.0.88：8182  # 配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    openfeign:
      lazy-attributes-resolution: true
  elasticsearch:
    uris: http://10.0.0.88:9200
    username: elastic
    password: jq1RRHIkpcp=8SKC5Tsi

management:
  endpoints:
    web:
      exposure:
        include: '*'


feign:
  sentinel:
    enabled: true