server:
  port: 8264


spring:
  application:
    name: ppeng-module-search
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 # 10.0.0.88:7744  # Nacos服务注册中心地址
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**

management:
  endpoints:
    web:
      exposure:
        include: '*'
