server:
  port: 8264

spring:
  application:
    name: ppeng-module-search
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080  # 配置Sentinel dashboard地址
        port: 8719 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
  elasticsearch:
    uris: http://****:9200
    username: elastic
    password: QSDJfBgRdFrD4Wg8BUtq



management:
  endpoints:
    web:
      exposure:
        include: '*'