server:
  port: 9836

spring:
  application:
    name: ppeng-module-recipe
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 #****:8848
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1       # 逻辑已删除
      logic-not-delete-value: 0   # 逻辑未删除

management:
  endpoints:
    web:
      exposure:
        include: '*'

