server:
  port: 9836

spring:
  application:
    name: ppeng-module-recipe
  output:
    ansi:
      enabled: always
  data:
    redis:
      database: 2
  cloud:
    nacos:
      discovery:
        server-addr: ****:8848
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**
    sentinel:
      transport:
        dashboard: ****:8976  # 配置Sentinel dashboard地址
        port: 8719                 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口


mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1       # 逻辑已删除
      logic-not-delete-value: 0   # 逻辑未删除

management:
  endpoints:
    web:
      exposure:
        include: '*'