server:
  port: 6378

spring:
  application:
    name: ppeng-module-gateway
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848  #****:8848 #****:7744
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**
    sentinel:
      transport:
        dashboard: 10.0.0.88:8182 #****:8182 # ****:8976    # 配置Sentinel dashboard地址
        port: 8719                 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    gateway:
      routes:
        # 用户模块
        - id: user_route
          uri: lb://ppeng-module-user
          predicates:
            - Path=/user/**
        # other-api模块
        - id: other_api_route
          uri: lb://ppeng-other-api
          predicates:
            - Path=/mail/**,/file/**,/image/recognition/**
        # 消息模块
        - id: message_route
          uri: lb://ppeng-module-message
          predicates:
            - Path=/message/**
        # 管理员模块
        - id: admin_route
          uri: lb://ppeng-module-admin
          predicates:
            - Path=/hidden/admin/**
        # 菜谱模块
        - id: recipe_route
          uri: lb://ppeng-module-recipe
          predicates:
            - Path=/recipe/**





management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'