server:
  port: 8888

spring:
  application:
    name: ppeng-module-gateway
  cloud:
    # redis配置
    redis:
      database: 0           # Redis数据库索引
      host: 47.115.207.226
      port: 6379
      password:
      timeout: 5000ms       # 连接超时时间
      lettuce:
        pool:
          max-active: 20    # 连接池最大连接数（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
          max-wait: 5000ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080  # 配置Sentinel dashboard地址
        port: 8719                 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    gateway:





management:
  endpoints:
    web:
      exposure:
        include: '*'
