server:
  port: 6378

spring:
  application:
    name: ppeng-module-gateway
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: ****:8848
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**
    sentinel:
      transport:
        dashboard: ****:8976  # 配置Sentinel dashboard地址
        port: 8719                 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    gateway:
      routes:
        - id: user_route
          uri: lb://ppeng-module-user
          predicates:
            - Path=/user/**


management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: '*'