server:
  port: 7679

spring:
  application:
    name: ppeng-module-admin
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848   # TODO 换成你的nacos地址，如果在同一docker网络下，填写容器名：端口号即可
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**      # TODO 换成你的nacos用户密码

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1       # 逻辑已删除
      logic-not-delete-value: 0   # 逻辑未删除



management:
  endpoints:
    web:
      exposure:
        include: '*'
