server:
  port: 3450

spring:
  application:
    name: ppeng-other-api
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 2048MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848 # TODO 换成你的nacos地址，如果在同一docker网络下，填写容器名：端口号即可
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**  # TODO 换成你的nacos用户密码