server:
  port: 3450

spring:
  application:
    name: ppeng-other-api
  output:
    ansi:
      enabled: always
  cloud:
    nacos:
      discovery:
        server-addr: ****:8848  #****:7744
        namespace: ppeng
        group: PPENG_GROUP
        username: ppeng
        password: **confidential**
    sentinel:
      transport:
        dashboard: ****:8182  # 配置Sentinel dashboard地址
        port: 8719                 # 默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
    openfeign:
      lazy-attributes-resolution: true
  mail:
    host: smtp.office365.com
    username: PPeng@****
    password: **confidential**
    default-encoding: UTF-8
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

feign:
  sentinel:
    enabled: true


management:
  health:
    redis:
      enabled: false